# Netlify Configuration for Auralo V2

[build]
  publish = "."

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(*), usb=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://api.simpleswap.io; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.simpleswap.io https://widget.mercuryo.io; frame-src https://widget.mercuryo.io; font-src 'self' data:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/javascript"

# Images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirects for payment
[[redirects]]
  from = "/pay-19"
  to = "https://simpleswap.io/exchange?from=usd-usd&to=pol-matic&amount=19"
  status = 302
  force = true

[[redirects]]
  from = "/pay-49"
  to = "https://simpleswap.io/exchange?from=usd-usd&to=pol-matic&amount=49"
  status = 302
  force = true